name: image_crop_example
description: Demonstrates how to use the image_crop plugin.

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.7.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

  images_crop:
    path: ../

flutter:
  uses-material-design: true
