name: images_crop
description: A flutter plugin to crop image on iOS and Android. It processes image files off main thread natively. The plugin provides a Crop widget to display image cropping to a user.
version: 0.1.0
homepage: https://github.com/VolodymyrLykhonis/image_crop

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  plugin_platform_interface: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
